module.exports = {
    qweqwe:
    //(领域模型的测试json数据)
    {id:"",//(null)
    name:"",//(测试数据的名字)  
    domainModel:{//所属领域模型
    propertySet:{//(模型属性分录)
    id:"",//(null)
    memo:"",//(备注)
    domainModel:null,//(所属领域模型)
    chineseName:"",//(属性中文名)
    propertyTypeEnum:"",//(属性类型枚举)
    name:"",//(属性名)
    baseType:""},//(所属简单类型)
    bosType:"",//(bos类型)
    id:"",//(null)
    name:"",//(中文名称)
    qualifiedName:""},//(类名全称)
    dataJson:""},//(测试数据json)
    test1:
    //(测试)
    {id:"",//(null)
    sex:0,//(性别)
    name:"",//(姓名)
    birthday:"",//(生日)
    phone:""},//(手机号)
    };